name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Check for 404s in modified files
        id: check_404_in_modified_files
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: 'main'
          use-quiet-mode: 'yes'
          check-modified-files-only: 'yes'
          file-extension: '.mdx'
          config-file: '.link_checker_config.json'

      - name: Capture and export output
        run: |
          echo "Action result: ${{ steps.check_404_in_modified_files.outputs.result }}"

    # - name: Write output to txt file
    #   if: always()
    #   run: |
    #     echo "azerzerz" > 404_list.txt
    #     echo "${{ steps.check_404_in_modified_files.outputs.stdout}}" > 404_list.txt
    