name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Check for 404s in modified files
      id: check_404_in_modified_files
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: 'main'
        use-quiet-mode: 'yes'
        check-modified-files-only: 'yes'
        file-extension: '.mdx'
        config-file: '.link_checker_config.json'

    - name: Write output to txt file
      run: echo "{{ steps.check_404_in_modified_files.outputs.*}} >> 404_list.txt"
    
    - name: Print content of txt file
      run: |
        echo "The following 404 have been detected:\n"
        cat 404_list.txt